[mgr]
prepend_keymap = [
	{ on = "?", run = 'help', desc = "Help" },
	{ on = "H", run = 'plugin duckdb -1', desc = "Scroll one column to the left" },
	{ on = "L", run = 'plugin duckdb +1', desc = "Scroll one column to the right" },
	# Sort by modified time (descending = newest first)
	{ on = [ ",", "m" ], run = "sort mtime --reverse=yes", desc = "Sort by modified time (newest first)" },
	# Sort by modified time (ascending = oldest first)
	{ on = [ ",", "M" ], run = "sort mtime --reverse=no", desc = "Sort by modified time (oldest first)" },
  # { on = "sr", run = 'S', desc = "fuzzy search ripgrep" },
]

[help]
prepend_keymap = [
	{ on = "/", run = 'filter', desc = "Filter" },
]

